FROM ghcr.io/graalvm/native-image:ol8-java17-22 AS builder

WORKDIR /build
COPY . .

RUN ./mvnw clean package -Pnative -DskipTests

FROM ubuntu:lunar-20230128 as runtime

EXPOSE 8080

COPY --from=builder /build/target/rtd-ms-sender-auth .

ENTRYPOINT ["./rtd-ms-sender-auth"]