logging:
  level:
    root: INFO

spring:
  application.name: rtdsenderauth
  config:
    activate:
      on-profile: default

  data:
    mongodb:
      uri: ${MONGODB_CONNECTION_URI:mongodb://localhost:27017}
      database: ${MONGODB_NAME:rtd}

management:
  metrics:
    enable:
      all: false
      process.cpu: true
      system.cpu: true
      jvm.memory: true
      application: true
  endpoints.web.exposure.include: health
  endpoint:
    health:
      probes:
        enabled: true

applicationinsights.enabled: '@applicationinsights.enabled@'
applicationinsights.connection-string: ${APPLICATIONINSIGHTS_CONNECTION_STRING:myconnectionstring}
otel.log.level: ${OPENTELEMETRY_LOG_LEVEL:INFO}
otel.instrumentation.logback-appender.enabled: true # enable logback instrumentation
otel.traces.sampler.probability: 1.0 # sample probability for tracing (spans)
otel.metric.export.interval: 60000 # sampling rate for metrics (millis)
