logging:
  level:
    root: INFO

spring:
  application.name: rtdsenderauth
  config:
    activate:
      on-profile: default

  data:
    mongodb:
      uri: ${MONGODB_CONNECTION_URI:mongodb://localhost:27017}
      database: ${MONGODB_NAME:rtd}

management:
  endpoints.web.exposure.include: health,metrics
  endpoint:
    health:
      probes:
        enabled: true

applicationinsights.enabled: ${@applicationinsights.enabled@:true}
otel.instrumentation.logback-appender.enabled: true # enable logback instrumentation
otel.traces.sampler.probability: 1.0 # sample probability for tracing (spans)
otel.metric.export.interval: 60000 # sampling rate for metrics (millis)
otel.exporter.otlp.enabled: false # disable send to OTLP endpoint


