logging:
  level:
    root: INFO

spring:
  application.name: rtdsenderauth
  config:
    activate:
      on-profile: default

  data:
    mongodb:
      uri: ${MONGODB_CONNECTION_URI:mongodb://localhost:27017}
      database: ${MONGODB_NAME:rtd}

management:
  metrics:
    mongo:
      commands.enabled: true
      connectionpool.enabled: true
    export.defaults.enabled: false
    enable:
      all: false
      process.cpu: false
      system.cpu: false
      jvm.memory: false
      application: false
  info.defaults.enabled: false
  endpoints:
    enabled-by-default: false
    web.exposure.include: health
  endpoint:
    health:
      show-details: always
      enabled: true
      probes:
        enabled: true

# OpenTelemetry
applicationinsights:
  enabled: '@applicationinsights.enabled@'
  connection-string: ${APPLICATIONINSIGHTS_CONNECTION_STRING:myconnectionstring}
otel:
  log:
    level: ${OPENTELEMETRY_LOG_LEVEL:INFO}
  traces:
    sampler:
      probability: 1.0 # sample probability for tracing (spans)
  metric:
    export:
      interval: 60000 # sampling rate for metrics (millis)
  instrumentation:
    logback-appender:
      enabled: true # enable logback instrumentation
    micrometer:
      enabled: false
