spring.application.name: rtd-ms-sender-auth-local
logging:
  level:
    root: INFO

spring:
  config:
    activate:
      on-profile: default

  data:
    mongodb:
      uri: ${MONGODB_CONNECTION_URI:mongodb://root:root@localhost:27017}
      database: ${MONGODB_NAME:rtd}

management:
  endpoints.web.exposure.include: health,metrics
  endpoint:
    health:
      probes:
        enabled: true

otel.instrumentation.logback-appender.enabled: false # enable logback instrumentation
otel.traces.sampler.probability: 1.0 # sample probability for tracing (spans)
otel.metric.export.interval: 60000 # sampling rate for metrics (millis)
otel.exporter.otlp.enabled: false # disable send to OTLP endpoint

applicationinsights:
  enabled: true
  connectionstring: ${APPINSIGHTS_CONNECTION_STRING}
