apiVersion: v2
name: rtd-ms-sender-auth
description: Micro-service responsible to store the association between sender code and api key.
type: application
version: 1.0.0
appVersion: 1.0.0
dependencies:
  - name: microservice-chart
    version: 3.0.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"