microservice-chart:
  namespace: "rtd"
  nameOverride: ""
  fullnameOverride: ""

  livenessProbe:
    handlerType: httpGet
    httpGet:
      path: /actuator/health/liveness
      port: 8080
    initialDelaySeconds: 5
    failureThreshold: 6
    periodSeconds: 5

  readinessProbe:
    handlerType: httpGet
    httpGet:
      path: /actuator/health/readiness
      port: 8080
    initialDelaySeconds: 5
    failureThreshold: 6
    periodSeconds: 5

  podAnnotations: { }

  deployment:
    create: true

  service:
    create: true
    type: ClusterIP
    ports:
      - 8080

  ingress:
    create: true
    path: /rtdmssenderauth/(.*)
    servicePort: 8080

  serviceAccount:
    name: "rtd-workload-identity" # Replace with your service account name if using workload identity
    # If using Azure Workload Identity, also add the azure section:
    azure:
      workloadIdentityClientId: "CHANGEME" # Insert your clientId here if needed

  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault

  securityContext:
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - all
    runAsNonRoot: true
    runAsUser: 10000
    runAsGroup: 10000

  envSecret:
    MONGODB_CONNECTION_URI: mongo-db-connection-uri
    APPLICATIONINSIGHTS_CONNECTION_STRING: appinsights-connection-string

  tmpVolumeMount:
    create: true
    mounts:
      - name: tmp
        mountPath: /tmp
      - name: logs
        mountPath: /app/logs

  externalConfigMapValues:
    rtdsenderauth:
      OPENTELEMETRY_LOG_LEVEL: APPLICATIONINSIGHTS_INSTRUMENTATION_LOGGING_LEVEL
