apiVersion: apps/v1
kind: Deployment
metadata:
  name: rtdmssenderauth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rtdmssenderauth
  template:
    metadata:
      labels:
        app: rtdmssenderauth
    spec:
      containers:
        - name: rtdmssenderauth
          image: rtdmssenderauth
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: rtdsenderauth
            - secretRef:
                name: application-insights
#             - secretRef:
#                 name: rtd-blob-storage-events
#             - secretRef:
#                 name: rtd-internal-api
            - secretRef:
                name: mongo-credentials
          resources:
            limits:
              cpu: 500m
              memory: 4Gi
            requests:
              cpu: 50m
              memory: 256Mi



